[package]
name = "findr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.17"
walkdir = "2"
regex = "1"

[dev-dependencies]
rand = "0.8"
assert_cmd = "2"
predicates = "2"
